# Generated by Django 3.1 on 2020-11-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(default=None)),
                ('x', models.CharField(max_length=30)),
                ('y', models.CharField(max_length=30)),
                ('date', models.DateField(default=None)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beds.bed')),
            ],
        ),
        migrations.CreateModel(
            name='PlantFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('first_date', models.DateField()),
                ('period', models.IntegerField()),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
