# Generated by Django 3.1 on 2020-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='x',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='y',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
