# Generated by Django 3.1 on 2020-11-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plantfunction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantfunction',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
