# Generated by Django 3.1 on 2020-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('description_weather', models.CharField(max_length=30)),
            ],
        ),
    ]
